# Generated by Django 5.1.2 on 2024-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст поста",
                        null=True,
                        verbose_name="Текст поста",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию к посту",
                        null=True,
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "publication_sign",
                    models.BooleanField(
                        default=False, verbose_name="Признак публикации"
                    ),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите кол-во просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
                "ordering": ["title"],
            },
        ),
    ]
