# Generated by Django 5.1.2 on 2024-10-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите кол-во просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
